export const MANUAL_IMAGE_SLUGS: Record<string, string> = {
    // A
    'Aigle': 'eagle',
    'Aigle géant': 'giant-eagle',
    'Acolyte': 'acolyte',
    'Allosaure': 'allosaurus',
    'Âme en peine': 'wraith',
    'Ankylosaure': 'ankylosaurus',
    'Araignée': 'spider',
    'Araignée géante': 'giant-spider',
    'Araignée de phase': 'phase-spider',
    'Araignée-loup géante': 'giant-wolf-spider',
    'Arbre éveillé': 'awakened-tree',
    'Arbuste éveillé': 'awakened-shrub',
    'Archimage': 'archmage',
    'Armure animée': 'animated-armor',
    'Assassin': 'assassin',
    'Azer': 'azer',

    // B
    'Babélien': 'gibbering-mouther',
    'Babouin': 'baboon',
    'Balor': 'balor',
    'Bandit': 'bandit',
    'Bandit, capitaine': 'bandit-captain',
    'Banshie': 'banshee',
    'Barlgura': 'barlgura',
    'Basilic': 'basilisk',
    'Bec de hache': 'axe-beak',
    'Béhir': 'behir',
    'Belette': 'weasel',
    'Belette géante': 'giant-weasel',
    'Bête éclipsante': 'displacer-beast',
    'Blaireau': 'badger',
    'Blaireau géant': 'giant-badger',
    'Blême': 'ghast',
    'Brutacien': 'bugbear',
    'Boulette': 'bulette',
    'Bullywug': 'bullywug',

    // C
    'Cambion': 'cambion',
    'Centaures': 'centaur',
    'Centaure': 'centaur',
    'Cerf': 'deer',
    'Chacal': 'jackal',
    'Chameau': 'camel',
    'Charognard rampant': 'carrion-crawler',
    'Chat': 'cat',
    'Chauve-souris': 'bat',
    'Chauve-souris géante': 'giant-bat',
    'Cheval de guerre': 'warhorse',
    'Cheval de selle': 'riding-horse',
    'Cheval de trait': 'draft-horse',
    'Chevalier': 'knight',
    'Chevalier de la mort': 'death-knight',
    'Chèvre': 'goat',
    'Chèvre géante': 'giant-goat',
    'Chien de chasse infernal': 'hell-hound',
    'Chien du trépas': 'death-dog',
    'Chien esquiveur': 'blink-dog',
    'Chimère': 'chimera',
    'Chouette': 'owl',
    'Chouette géante': 'giant-owl',
    'Cockatrice': 'cockatrice',
    'Corbeau': 'raven',
    'Couatl': 'couatl',
    'Crabe': 'crab',
    'Crabe géant': 'giant-crab',
    'Crânefeu': 'flameskull',
    'Crapaud géant': 'giant-toad',
    'Criard': 'shrieker',
    'Crocodile': 'crocodile',
    'Crocodile géant': 'giant-crocodile',
    'Cube gélatineux': 'gelatinous-cube',
    'Cultiste': 'cultist',
    'Cyclope': 'cyclops',

    // D
    'Demi-dragon rouge, vétéran': 'half-red-dragon-veteran',
    'Demi-liche': 'demilich',
    'Demiliche': 'demilich',
    'Demi-ogre': 'half-ogre',
    'Démon des ombres': 'shadow-demon',
    'Destrier noir': 'nightmare',
    'Déva': 'deva',
    'Dévoreur d\'intellect': 'intellect-devourer',
    'Diable à chaînes': 'chain-devil',
    'Diable barbelé': 'barbed-devil',
    'Diable barbu': 'bearded-devil',
    'Diable cornu': 'horned-devil',
    'Diable épineux': 'spined-devil',
    'Diable gelé': 'ice-devil',
    'Diable osseux': 'bone-devil',
    'Diablotin': 'imp',
    'Diantrefosse': 'pit-fiend',
    'Doppelganger': 'doppelganger',
    'Dracoliche bleue, adulte': 'adult-blue-dracolich',
    'Dragon blanc, adulte': 'adult-white-dragon',
    'Dragon blanc, ancien': 'ancient-white-dragon',
    'Dragon blanc, dragonnet': 'white-dragon-wyrmling',
    'Dragon blanc, jeune': 'young-white-dragon',
    'Dragon bleu, adulte': 'adult-blue-dragon',
    'Dragon bleu, ancien': 'ancient-blue-dragon',
    'Dragon bleu, dragonnet': 'blue-dragon-wyrmling',
    'Dragon bleu, jeune': 'young-blue-dragon',
    'Dragon d\'airain, adulte': 'adult-brass-dragon',
    'Dragon d\'airain, ancien': 'ancient-brass-dragon',
    'Dragon d\'airain, dragonnet': 'brass-dragon-wyrmling',
    'Dragon d\'airain, jeune': 'young-brass-dragon',
    'Dragon d\'argent, adulte': 'adult-silver-dragon',
    'Dragon d\'argent, ancien': 'ancient-silver-dragon',
    'Dragon d\'argent, dragonnet': 'silver-dragon-wyrmling',
    'Dragon d\'argent, jeune': 'young-silver-dragon',
    'Dragon d\'ombre rouge, jeune': 'young-red-shadow-dragon',
    'Dragon d\'or, adulte': 'adult-gold-dragon',
    'Dragon d\'or, ancien': 'ancient-gold-dragon',
    'Dragon d\'or, dragonnet': 'gold-dragon-wyrmling',
    'Dragon d\'or, jeune': 'young-gold-dragon',
    'Dragon de bronze, adulte': 'adult-bronze-dragon',
    'Dragon de bronze, ancien': 'ancient-bronze-dragon',
    'Dragon de bronze, dragonnet': 'bronze-dragon-wyrmling',
    'Dragon de bronze, jeune': 'young-bronze-dragon',
    'Dragon de cuivre, adulte': 'adult-copper-dragon',
    'Dragon de cuivre, ancien': 'ancient-copper-dragon',
    'Dragon de cuivre, dragonnet': 'copper-dragon-wyrmling',
    'Dragon de cuivre, jeune': 'young-copper-dragon',
    'Dragon féerique': 'faerie-dragon',
    'Dragon noir, adulte': 'adult-black-dragon',
    'Dragon noir, ancien': 'ancient-black-dragon',
    'Dragon noir, dragonnet': 'black-dragon-wyrmling',
    'Dragon noir, jeune': 'young-black-dragon',
    'Dragon rouge, adulte': 'adult-red-dragon',
    'Dragon rouge, ancien': 'ancient-red-dragon',
    'Dragon rouge, dragonnet': 'red-dragon-wyrmling',
    'Dragon rouge, jeune': 'young-red-dragon',
    'Dragon vert, adulte': 'adult-green-dragon',
    'Dragon vert, ancien': 'ancient-green-dragon',
    'Dragon vert, dragonnet': 'green-dragon-wyrmling',
    'Dragon vert, jeune': 'young-green-dragon',
    'Dragon-tortue': 'dragon-turtle',
    'Draragne': 'drider',
    'Dretch': 'dretch',
    'Drider': 'drider',
    'Drow': 'drow',
    'Drow, guerrier d\'élite': 'drow-elite-warrior',
    'Drow, mage': 'drow-mage',
    'Drow, prêtresse de Lolth': 'drow-priestess-of-lolth',
    'Druide': 'druid',
    'Dryade': 'dryad',
    'Duergar': 'duergar',
    'Duodrone': 'duodrone',

    // E
    'Éclaireur': 'scout',
    'Éfrit': 'efreeti',
    'Elan': 'elk',
    'Élan': 'elk',
    'Élan géant': 'giant-elk',
    'Eléphant': 'elephant',
    'Éléphant': 'elephant',
    'Élémentaire de l\'air': 'air-elemental',
    'Élémentaire de l\'eau': 'water-elemental',
    'Élémentaire de la terre': 'earth-elemental',
    'Élémentaire du feu': 'fire-elemental',
    'Empyréen': 'empyrean',
    'Enlaceur': 'roper',
    'Ent': 'treant',
    'Épaulard': 'killer-whale',
    'Épée volante': 'flying-sword',
    'Épouvantail': 'scarecrow',
    'Érinye': 'erinyes',
    'Espion': 'spy',
    'Esprit follet': 'sprite',
    'Ettercap': 'ettercap',
    'Ettin': 'ettin',

    // F
    'Fanatique': 'cult-fanatic',
    'Fantôme': 'ghost',
    'Faucon': 'hawk',
    'Faucon de sang': 'blood-hawk',
    'Feu follet': 'will-o-wisp',
    'Flagelleur mental': 'mind-flayer',
    'Flumph': 'flumph',
    'Fomorian': 'fomorian',
    'Fomorien': 'fomorian',

    // G
    'Galeb Duhr': 'galeb-duhr',
    'Galeb duhr': 'galeb-duhr',
    'Garde': 'guard',
    'Gardien animé': 'shield-guardian',
    'Gargouille': 'gargoyle',
    'Garou-chacal': 'jackalwere',
    'Géant': 'giant',
    'Géant des collines': 'hill-giant',
    'Géant des nuages': 'cloud-giant',
    'Géant des pierres': 'stone-giant',
    'Géant des tempêtes': 'storm-giant',
    'Géant du feu': 'fire-giant',
    'Géant du givre': 'frost-giant',
    'Gelée ocre': 'ochre-jelly',
    'Gibbering Mouther': 'gibbering-mouther',
    'Giff': 'giff',
    'Githyanki, chevalier': 'githyanki-knight',
    'Githyanki, guerrier': 'githyanki-warrior',
    'Githzerai, moine': 'githzerai-monk',
    'Githzerai, zerth': 'githzerai-zerth',
    'Glabrezu': 'glabrezu',
    'Gladiateur': 'gladiator',
    'Gnoll': 'gnoll',
    'Gnoll, croc de Yeenoghu': 'gnoll-fang-of-yeenoghu',
    'Gnoll, seigneur de meute': 'gnoll-pack-lord',
    'Gnome': 'gnome',
    'Gnome des profondeurs (svirfnebelin)': 'deep-gnome',
    'Gobelin': 'goblin',
    'Gobelin, chef': 'goblin-boss',
    'Gobelours': 'bugbear',
    'Gobelours, chef': 'bugbear-chief',
    'Golem': 'golem',
    'Golem d\'argile': 'clay-golem',
    'Golem de chair': 'flesh-golem',
    'Golem de fer': 'iron-golem',
    'Golem de pierre': 'stone-golem',
    'Gorgone': 'gorgon',
    'Goristro': 'goristro',
    'Goule': 'ghoul',
    'Grand singe': 'ape',
    'Grell': 'grell',
    'Grenouille': 'frog',
    'Grenouille géante': 'giant-frog',
    'Grick': 'grick',
    'Grick dominant': 'grick-alpha',
    'Griffe rampante': 'crawling-claw',
    'Griffon': 'griffon',
    'Grimlock': 'grimlock',
    'Grizzly': 'brown-bear',
    'Guenaude': 'hag',
    'Guenaude marine': 'sea-hag',
    'Guenaude nocturne': 'night-hag',
    'Guenaude verte': 'green-hag',
    'Guêpe géante': 'giant-wasp',
    'Guerrier': 'warrior',
    'Guerrier tribal': 'tribal-warrior',
    'Gynosphinx': 'gynosphinx',

    // H
    'Harpie': 'harpy',
    'Hell Hound': 'hell-hound',
    'Hezrou': 'hezrou',
    'Hippocampe': 'hippocampus',
    'Hippocampe géant': 'giant-seahorse',
    'Hippogriffe': 'hippogriff',
    'Hobgobelin': 'hobgoblin',
    'Hobgobelin, capitaine': 'hobgoblin-captain',
    'Hobgobelin, seigneur de guerre': 'hobgoblin-warlord',
    'Homme-lézard': 'lizardfolk',
    'Homme-lézard, chaman': 'lizardfolk-shaman',
    'Homme-poisson': 'merfolk',
    'Homoncule': 'homunculus',
    'Hook Horror': 'hook-horror',
    'Horreur casquée': 'helmed-horror',
    'Horreur crochue': 'hook-horror',
    'Hydre': 'hydra',
    'Hyène': 'hyena',
    'Hyène géante': 'giant-hyena',

    // I, J
    'Intellect Devourer': 'intellect-devourer',
    'Invisible Stalker': 'invisible-stalker',

    // K, L
    'Jackalwere': 'jackalwere',
    'Kenku': 'kenku',
    'Kobold': 'kobold',
    'Kobold ailé': 'winged-kobold',
    'Kraken': 'kraken',
    'Kuo-toa': 'kuo-toa',
    'Kuo-toa, archiprêtre': 'kuo-toa-archpriest',
    'Kuo-toa, fouet': 'kuo-toa-whip',

    'Lamie': 'lamia',
    'Lemure': 'lemure',
    'Lémure': 'lemure',
    'Lézard': 'lizard',
    'Lézard géant': 'giant-lizard',
    'Liche': 'lich',
    'Licorne': 'unicorn',
    'Lierreux': 'vine-blight',
    'Lion': 'lion',
    'Lizardfolk': 'lizardfolk',
    'Loup': 'wolf',
    'Loup arctique': 'winter-wolf',
    'Loup sanguinaire': 'dire-wolf',
    'Loup-garou': 'werewolf',

    // M
    'Mage': 'mage',
    'Magmatique': 'magmin',
    'Malfrat': 'thug',
    'Mammouth': 'mammoth',
    'Mâne': 'manes',
    'Mante obscure': 'darkmantle',
    'Manteleur': 'cloaker',
    'Manticore': 'manticore',
    'Maride': 'marid',
    'Marilith': 'marilith',
    'Mastodonte des ombres': 'shadow-mastiff',
    'Medusa': 'medusa',
    'Méduse': 'medusa',
    'Méphite boueux': 'mud-mephit',
    'Méphite fumant': 'smoke-mephit',
    'Méphite gelé': 'ice-mephit',
    'Méphite magmatique': 'magma-mephit',
    'Méphite poussiéreux': 'dust-mephit',
    'Méphite vaporeux': 'steam-mephit',
    'Mephit': 'mephit',
    'Merrow': 'merrow',
    'Mezzoloth': 'mezzoloth',
    'Mille-pattes géant': 'giant-centipede',
    'Mimique': 'mimic',
    'Minotaure': 'minotaur',
    'Moisissure violette': 'violet-fungus',
    'Molosse': 'mastiff',
    'Momie': 'mummy',
    'Mongrelfolk': 'mongrelfolk',
    'Monodrone': 'monodrone',
    'Mule': 'mule',
    'Myconid': 'myconid',
    'Myconide, adulte': 'myconid-adult',
    'Myconide, pousse': 'myconid-sprout',
    'Myconide, souverain': 'myconid-sovereign',

    // N
    'Naga': 'naga',
    'Naga corrupteur': 'spirit-naga',
    'Naga gardien': 'guardian-naga',
    'Naga osseux': 'bone-naga',
    'Nalfeshnie': 'nalfeshnie',
    'Nécrophage': 'wight',
    'Nielleux': 'needle-blight',
    'Noble': 'noble',
    'Nothic': 'nothic',
    'Nuée d\'insectes': 'swarm-of-insects',
    'Nuée de chauves-souris': 'swarm-of-bats',
    'Nuée de corbeaux': 'swarm-of-ravens',
    'Nuée de piranhas': 'swarm-of-quippers',
    'Nuée de rats': 'swarm-of-rats',
    'Nuée de serpents venimeux': 'swarm-of-poisonous-snakes',
    'Nycaloth': 'nycaloth',

    // O
    'Ogre': 'ogre',
    'Ombre': 'shadow',
    'Oni': 'oni',
    'Ooze': 'ooze',
    'Orc': 'orc',
    'Orc, chef de guerre': 'orc-war-chief',
    'Orc, Oeil de Gruumsh': 'orc-eye-of-gruumsh',
    'Orog': 'orog',
    'Otyugh': 'otyugh',
    'Ours brun': 'brown-bear',
    'Ours noir': 'black-bear',
    'Ours polaire': 'polar-bear',
    'Ours-garou': 'werebear',
    'Ours-hibou': 'owlbear',
    'Oxydeur': 'rust-monster',

    // P
    'Panthère': 'panther',
    'Pégase': 'pegasus',
    'Pentadrone': 'pentadrone',
    'Perceur': 'piercer',
    'Peryton': 'peryton',
    'Péryton': 'peryton',
    'Pieuvre': 'octopus',
    'Pieuvre géante': 'giant-octopus',
    'Piranha': 'quipper',
    'Pixie': 'pixie',
    'Planétar': 'planetar',
    'Plésiosaure': 'plesiosaurus',
    'Poney': 'pony',
    'Pouding noir': 'black-pudding',
    'Prêtre': 'priest',
    'Pseudodragon': 'pseudodragon',
    'Ptéranodon': 'pteranodon',
    'Purple Worm': 'purple-worm',

    // Q, R
    'Quadrone': 'quadrone',
    'Quaggoth': 'quaggoth',
    'Quaggoth, serviteur des spores': 'quaggoth-spore-servant',
    'Quasit': 'quasit',
    'Rakshasa': 'rakshasa',
    'Rat': 'rat',
    'Rat géant': 'giant-rat',
    'Rat-garou': 'wererat',
    'Remorhaz': 'remorhaz',
    'Remorhaz, jeune': 'young-remorhaz',
    'Requin de récif': 'reef-shark',
    'Requin géant': 'giant-shark',
    'Requin-chasseur': 'hunter-shark',
    'Résinieux': 'treant',
    'Revenant': 'revenant',
    'Rhinocéros': 'rhinoceros',
    'Roc': 'roc',
    'Roi/reine lézard': 'lizard-king',
    'Roper': 'roper',
    'Roturier': 'commoner',
    'Rust Monster': 'rust-monster',

    // S
    'Sahuagin': 'sahuagin',
    'Sahuagin, baron': 'sahuagin-baron',
    'Sahuagin, prêtresse': 'sahuagin-priestess',
    'Salamandre': 'salamander',
    'Sanglier': 'boar',
    'Sanglier géant': 'giant-boar',
    'Sanglier-garou': 'wereboar',
    'Satyre': 'satyr',
    'Scarabée de feu géant': 'giant-fire-beetle',
    'Scarecrow': 'scarecrow',
    'Scorpion': 'scorpion',
    'Scorpion géant': 'giant-scorpion',
    'Seigneur momie': 'mummy-lord',
    'Sentinelle d\'eau': 'water-weird',
    'Serpent constricteur': 'constrictor-snake',
    'Serpent constricteur géant': 'giant-constrictor-snake',
    'Serpent de feu': 'fire-snake',
    'Serpent venimeux': 'poisonous-snake',
    'Serpent venimeux géant': 'giant-poisonous-snake',
    'Serpent volant': 'flying-snake',
    'Shambling Mound': 'shambling-mound',
    'Shield Guardian': 'shield-guardian',
    'Singe géant': 'giant-ape',
    'Slaad': 'slaad',
    'Slaad bleu': 'blue-slaad',
    'Slaad funeste': 'death-slaad',
    'Slaad gris': 'gray-slaad',
    'Slaad rouge': 'red-slaad',
    'Slaad vert': 'green-slaad',
    'Slaad, têtard': 'slaad-tadpole',
    'Solar': 'solar',
    'Spectateur': 'spectator',
    'Spectre': 'specter',
    'Sphinx': 'sphinx',
    'Spore gazeuse': 'gas-spore',
    'Sprite': 'sprite',
    'Squelette': 'skeleton',
    'Squelette de cheval de guerre': 'warhorse-skeleton',
    'Squelette de minotaure': 'minotaur-skeleton',
    'Stirge': 'stirge',
    'Strige': 'stirge',
    'Succube': 'succubus',
    'Sylvanien': 'treant',

    // T
    'Tapis étouffant': 'rug-of-smothering',
    'Tarasque': 'tarrasque',
    'Tarrasque': 'tarrasque',
    'Tertre errant': 'shambling-mound',
    'Thri-kreen': 'thri-kreen',
    'Tigre': 'tiger',
    'Tigre à dents de sabre': 'saber-toothed-tiger',
    'Tigre-garou': 'weretiger',
    'Titan': 'titan',
    'Torve': 'nothic',
    'Traqueur invisible': 'invisible-stalker',
    'Tricératops': 'triceratops',
    'Tridrone': 'tridrone',
    'Troglodyte': 'troglodyte',
    'Troll': 'troll',
    'Tyramort': 'death-tyrant',
    'Tyrannoeil': 'beholder',
    'Tyrannosaure': 'tyrannosaurus-rex',

    // U
    'Ultroloth': 'ultroloth',
    'Umber Hulk': 'umber-hulk',

    // V
    'Vampire': 'vampire',
    'Vampirien': 'vampire-spawn',
    'Vargouille': 'vargouille',
    'Vase grise': 'gray-ooze',
    'Vautour': 'vulture',
    'Vautour géant': 'giant-vulture',
    'Ver pourpre': 'purple-worm',
    'Vétéran': 'veteran',
    'Vrock': 'vrock',

    // W, X, Y, Z
    'Wight': 'wight',
    'Wiverne': 'wyvern',
    'Worg': 'worg',
    'Wraith': 'wraith',
    'Wyvern': 'wyvern',
    'Xorn': 'xorn',
    'Yéti': 'yeti',
    'Yéti abominable': 'abominable-yeti',
    'Yochlol': 'yochlol',
    'Yuan-ti': 'yuan-ti',
    'Yuan-ti, abomination': 'yuan-ti-abomination',
    'Yuan-ti, malison': 'yuan-ti-malison',
    'Yuan-ti, sang-pur': 'yuan-ti-pureblood',
    'Zombi': 'zombie',
    'Zombi ogre': 'ogre-zombie',
    'Zombi tyrannoeil': 'beholder-zombie',
    'Zombie': 'zombie'
};
