version: '3.8'

services:
  trame:
    image: trame:latest
    container_name: trame
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - NODE_ENV=production
      # Mettez ici l'URL de votre NAS si accessible de l'extérieur, ou localhost si testé en local
      # - PRODUCTION_URL=http://votre-nas-ip:3000
    ports:
      - "3000:8080"
